spring.datasource.url=jdbc:postgresql://localhost:5432/araripe_invest_test
spring.datasource.username=test
spring.datasource.password=test

spring.jpa.hibernate.ddl-auto=validate

management.endpoint.health.show-details=always
araripe.jobs.daily-flow.enabled=false
