spring.datasource.url=${ARARIPE_DB_URL}
spring.datasource.username=${ARARIPE_DB_USERNAME}
spring.datasource.password=${ARARIPE_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate


araripe.integrations.brapi.token=${BRAPI_TOKEN}

management.endpoint.health.show-details=never
