spring.datasource.url=jdbc:postgresql://${ARARIPE_DB_HOST:localhost}:${ARARIPE_DB_PORT:5432}/${ARARIPE_DB_NAME:araripe_invest}
spring.datasource.username=${ARARIPE_DB_USERNAME:araripe}
spring.datasource.password=${ARARIPE_DB_PASSWORD:araripe_local_password}

spring.jpa.hibernate.ddl-auto=validate

management.endpoint.health.show-details=when_authorized
