spring.datasource.url=${ARARIPE_DB_URL}
spring.datasource.username=${ARARIPE_DB_USERNAME}
spring.datasource.password=${ARARIPE_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

spring.ai.model.chat=${SPRING_AI_MODEL_CHAT:openai}
spring.ai.openai.api-key=${OPENAI_API_KEY}

araripe.integrations.brapi.token=${BRAPI_TOKEN}

management.endpoint.health.show-details=never
