package com.freirelts.araripe_invest_api.domain.thesis;

public enum ThesisStatus {
	DADOS_INSUFICIENTES,
	EM_ESTUDO,
	CRITERIOS_ATENDIDOS,
	CRITERIOS_PARCIALMENTE_ATENDIDOS,
	PREMISSAS_ALTERADAS,
	DADOS_DESATUALIZADOS
}
