package com.freirelts.araripe_invest_api.application.screening;

public enum EliminatoryFilterCode {
	INSUFFICIENT_LIQUIDITY,
	PRICE_BELOW_MINIMUM,
	MINIMUM_FUNDAMENTALS_MISSING,
	RECURRING_LOSSES,
	PERSISTENT_NEGATIVE_FREE_CASHFLOW,
	EXCESSIVE_DEBT,
	STRONG_FUNDAMENTAL_DETERIORATION,
	STRONG_REVENUE_DETERIORATION,
	STRONG_EARNINGS_DETERIORATION,
	NEGATIVE_PROFIT_MARGIN,
	EXTREME_VALUATION_WITHOUT_GROWTH,
	LONG_TREND_DETERIORATED,
	EXTREME_VOLATILITY,
	DATA_QUALITY_BLOCKED
}
