ALTER TABLE position_theses DROP CONSTRAINT ck_position_theses_status;
ALTER TABLE job_runs DROP CONSTRAINT ck_job_runs_name;

UPDATE position_theses
SET status = CASE status
    WHEN 'IGNORAR' THEN 'DADOS_INSUFICIENTES'
    WHEN 'MONITORAR' THEN 'EM_ESTUDO'
    WHEN 'OPORTUNIDADE' THEN 'CRITERIOS_ATENDIDOS'
    WHEN 'APORTE_PLANEJADO' THEN 'CRITERIOS_ATENDIDOS'
    WHEN 'REAVALIAR' THEN 'PREMISSAS_ALTERADAS'
    WHEN 'REDUZIR_EXPOSICAO' THEN 'PREMISSAS_ALTERADAS'
    WHEN 'SAIR_DA_TESE' THEN 'PREMISSAS_ALTERADAS'
    ELSE status
END
WHERE status IN ('IGNORAR', 'MONITORAR', 'OPORTUNIDADE', 'APORTE_PLANEJADO', 'REAVALIAR', 'REDUZIR_EXPOSICAO', 'SAIR_DA_TESE');

UPDATE job_runs
SET job_name = 'SCREENER'
WHERE job_name = 'RANKING';

ALTER TABLE position_theses
    ADD CONSTRAINT ck_position_theses_status
        CHECK (status IN (
            'DADOS_INSUFICIENTES',
            'EM_ESTUDO',
            'CRITERIOS_ATENDIDOS',
            'CRITERIOS_PARCIALMENTE_ATENDIDOS',
            'PREMISSAS_ALTERADAS',
            'DADOS_DESATUALIZADOS'
        ));

ALTER TABLE job_runs
    ADD CONSTRAINT ck_job_runs_name
        CHECK (job_name IN (
            'DAILY_MARKET_DATA_COLLECTION',
            'FUNDAMENTAL_DATA_COLLECTION',
            'INDICATOR_CALCULATION',
            'FILTERS_AND_THESES',
            'SCREENER',
            'AI_CONTEXT_ENRICHMENT',
            'PORTFOLIO_SCAN',
            'DAILY_NOTIFICATION_DIGEST',
            'DAILY_OPERATIONAL_FLOW'
        ));
