package com.freirelts.araripe_invest_api.domain.jobs;

public enum JobName {
	DAILY_MARKET_DATA_COLLECTION,
	FUNDAMENTAL_DATA_COLLECTION,
	INDICATOR_CALCULATION,
	FILTERS_AND_THESES,
	RANKING,
	AI_CONTEXT_ENRICHMENT,
	PORTFOLIO_SCAN,
	DAILY_NOTIFICATION_DIGEST,
	DAILY_OPERATIONAL_FLOW
}
